### ISSUE TITLE
Document parsenvy.tuple

### ISSUE THREAD

**Issue by nkantar** [nkantar/Parsenvy#21]
The `tuple` function needs to be documented.

## To-do:

- [x] Add function docstring
- [x] Add any relevant inline comments
- [x] Add to project docs
    - [x] `autodoc` reference
    - [x] Any additional information
- [x] double-check tests for any additional edge cases

## Tips:

- For the function docstring, you can run `make doccheck` and only pay attention to the errors related to your changes.
- For the project docs, you can run `make doccheck` and then refresh the documentation in your browser. Docs homepage is `docs/build/html/index.html`.

**Comment by polkapolka** [comment]
Ok I am doing this one.
