### ISSUE TITLE
Document parsenvy.set

### ISSUE THREAD

**Issue by nkantar** [nkantar/Parsenvy#23]
The `set` function needs to be documented.

## To-do:

- [ ] Add function docstring
- [ ] Add any relevant inline comments
- [ ] Add to project docs
    - [ ] `autodoc` reference
    - [ ] Any additional information
- [ ] double-check tests for any additional edge cases

## Tips:

- For the function docstring, you can run `make doccheck` and only pay attention to the errors related to your changes.
- For the project docs, you can run `make doccheck` and then refresh the documentation in your browser. Docs homepage is `docs/build/html/index.html`.

**Comment by polkapolka** [comment]
Go for 100%
